/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    ContactView: typeof import('./src/components/ContactView.vue')['default']
    DescriptionView: typeof import('./src/components/DescriptionView.vue')['default']
    FooterView: typeof import('./src/components/FooterView.vue')['default']
    OurCafeExperience: typeof import('./src/components/OurCafeExperience.vue')['default']
    OurDelightsView: typeof import('./src/components/OurDelightsView.vue')['default']
    ProductsSlide: typeof import('./src/components/ProductsSlide.vue')['default']
    ProductsSlideSlider: typeof import('./src/components/ProductsSlideSlider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VisitOurCafe: typeof import('./src/components/VisitOurCafe.vue')['default']
    WorkView: typeof import('./src/components/WorkView.vue')['default']
  }
}
